name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build & test
        run: |
          npm install
          npm run lint
          npm run build
          npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
